-- MySQL Script generated by MySQL Workbench
-- 09/23/16 13:59:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Article` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `Source` VARCHAR(500) NULL,
  `SourceId` VARCHAR(500) NULL,
  `XML` LONGTEXT NULL,
  PRIMARY KEY (`idArticle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(500) NULL,
  `u_Password` VARCHAR(500) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `ProjectName` VARCHAR(500) NULL,
  `ProjectDescription` VARCHAR(800) NULL,
  `OwnerId` INT NOT NULL,
  `DateCreated` VARCHAR(200) NULL,
  PRIMARY KEY (`idProject`, `OwnerId`),
  UNIQUE INDEX `idProject_UNIQUE` (`idProject` ASC),
  INDEX `fk_Project_User1_idx` (`OwnerId` ASC),
  CONSTRAINT `fk_Project_User1`
    FOREIGN KEY (`OwnerId`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Annotation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Annotation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Annotation` (
  `idAnnotation` INT NOT NULL AUTO_INCREMENT,
  `XPath` VARCHAR(1000) NULL,
  `type` VARCHAR(500) NULL,
  `idLabel` VARCHAR(500) NULL,
  `subj` VARCHAR(500) NULL,
  `pred` VARCHAR(500) NULL,
  `obj` VARCHAR(500) NULL,
  `Article_idArticle` INT NOT NULL,
  `Project_idProject` INT NOT NULL,
  `span_start` INT NULL,
  `span_end` INT NULL,
  PRIMARY KEY (`idAnnotation`, `Article_idArticle`, `Project_idProject`),
  INDEX `fk_Annotation_Article_idx` (`Article_idArticle` ASC),
  INDEX `fk_Annotation_Project1_idx` (`Project_idProject` ASC),
  CONSTRAINT `fk_Annotation_Article`
    FOREIGN KEY (`Article_idArticle`)
    REFERENCES `mydb`.`Article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annotation_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `mydb`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ActiveSessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ActiveSessions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ActiveSessions` (
  `idActiveSessions` INT NOT NULL AUTO_INCREMENT,
  `Token` VARCHAR(500) NULL,
  `Expires` DATETIME NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idActiveSessions`, `User_idUser`),
  INDEX `fk_ActiveSessions_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_ActiveSessions_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
